---
title: "Prediction Assignment Writeup"
output: html_document
---

Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. 

"Six young health participants were asked to perform one set of 10 repetitions of the Unilateral Dumbbell Biceps Curl in five different fashions: exactly according to the specification (Class A), throwing the elbows to the front (Class B), lifting the dumbbell only halfway (Class C), lowering the dumbbell only halfway (Class D) and throwing the hips to the front (Class E)."

This human activity recognition research has traditionally focused on discriminating between different activities, i.e. to predict "which" activity was performed at a specific point in time (like with the Daily Living Activities dataset above).   

In this project I will try to predict "which" activity (exactly according to the specication (Class A) , throwing the elbows to the front (Class B), lifting the dumbbell only halfway (Class C), lowering the dumbbell only halfway (Class D) and throwing the hips to the front (Class E).) was performed at a specific point in time.   


The data has been downloaded from the http://groupware.les.inf.puc-rio.br/har website. The train and test data the will be used in the project is provided. Before 

## Loading and preprocessing the data

```{r loadData}
    library(caret)
    # set working directory
    setwd("C:/rproj/data_science/Practical_Machine_Learning/week3/assign")
    training <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")
    testing <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")
```
